name: Build & Publish rates.json

on:
  schedule:
    - cron: "*/5 * * * *"   # каждые 5 минут
  workflow_dispatch: {}      # запуск вручную

# даём воркфлоу право пушить в gh-pages
permissions:
  contents: write

# чтобы новые запуски отменяли предыдущие
concurrency:
  group: rates-build
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node 20 (с кэшем npm)
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Cache Playwright browsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: pw-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            pw-${{ runner.os }}-

      - name: Install deps (+ Chromium для Playwright)
        run: |
          npm ci || npm i
          npx playwright install --with-deps chromium

      - name: Build rates.json
        run: npm run build   # должен вызвать scripts/build.js

      # --- этот шаг добавляет index.html в корень gh-pages,
      # чтобы по адресу / не было 404 и можно было увидеть JSON
      - name: Add index.html (viewer для корня)
        run: |
          mkdir -p dist
          cat > dist/index.html << 'HTML'
          <!doctype html>
          <meta charset="utf-8">
          <title>poeopt-rates</title>
          <style>
            :root { color-scheme: dark light }
            body{font:14px/1.5 system-ui,Arial;padding:24px;background:#0b0b0b;color:#eee}
            a{color:#ffd166}
            pre{white-space:pre-wrap}
          </style>
          <h1>poeopt-rates</h1>
          <p>Данные: <a href="rates.json">rates.json</a></p>
          <pre id="out">loading…</pre>
          <script>
            fetch('rates.json').then(r=>r.json()).then(j=>{
              out.textContent = JSON.stringify(j,null,2);
            }).catch(e=>{ out.textContent = 'Error: '+e; });
          </script>
          HTML

      - name: Publish to gh-pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: dist
          clean: true
